project_name: coralcert

builds:
  - binary: coralcert
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - solaris
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm

brew:
  github:
    owner: coralproject
    name: homebrew-stable
  folder: Formula
  homepage:  https://github.com/coralproject/coralcert
  description: Secret Generation for The Coral Project's Talk product.
  test: |
    system "#{bin}/coralcert -v"

archive:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE.md
    - README.md

release:
  github:
    owner: coralproject
    name: coralcert